### ISSUE TITLE
Created zip files do not open on Mac's default archive utility

### ISSUE THREAD

**Issue by aniketbhatnagar** [koofr/zipstream#4]
Not sure why but the created zip files on Mac's default archive utility. Zip command line utility is able to extract files and so is Mac's the unarchiver utility.

**Comment by nelsonblaha** [comment]
Me too

**Comment by kirked** [comment]
Alternative that works: https://gist.github.com/kirked/412b5156f94419e71ce4a84ec1d54761

**Comment by nelsonblaha** [comment]
thanks @kirked , you da real MVP
