### ISSUE TITLE
License / maven repo not working

### ISSUE THREAD

**Issue by konradwudkowski** [koofr/zipstream#5]
Hi,

I would very much like to use this code. Your maven repo doesn't seem to work unfortunately.
Also would it be possible to include a license for this please.

Thanks a lot in advance! - Konrad

**Comment by bancek** [comment]
Hi

I've added `LICENSE` file and updated sample project to use Maven repo.

https://github.com/koofr/zipstream/commit/7842f53a74f99a6ed62711a8e85ba426338834c4

It seems to be working.
